### ISSUE TITLE
Fails to resolve local dependency

### ISSUE THREAD

**Issue by wbrickner** [nicholasbishop/aws-build#4]
`$ aws-build al2 --rust-version nightly`

fails because my `Cargo.toml` contains

```toml
[dependencies]
my_library = { path = "../libs/my_library" }
```

How do I move this directory into the docker container so that it can be found during build?

Thank you!
